// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnxctqfrmhvvzukvsjnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxueGN0cWZybWh2dnp1a3Zzam5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MTI0MzksImV4cCI6MjA1NTI4ODQzOX0.RLl5uXZorI1RsFz7Q6X_HLqRf1KeaFjViZSHMK5KnbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);